### ISSUE TITLE
no response_data.p

### ISSUE THREAD

**Issue by zpitroda** [puffyboa/virtual-assistant#25]
it cant open the file because it doesn't exist, and when I add it I get the error that its empty. It wont run without one

**Comment by zpitroda** [comment]
On first run:
`Generating response data...
Traceback (most recent call last):
  File "C:\Users\zpit3\OneDrive\Documents\GitHub\virtual-assistant\main.py", line 92, in <module>
    with open(currentDir + '/response_data.p','wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\zpit3\\OneDrive\\Documents\\GitHub\\virtual-assistant/response_data.p'`

after adding the file:
`Traceback (most recent call last):
  File "C:\Users\zpit3\OneDrive\Documents\GitHub\virtual-assistant\main.py", line 86, in <module>
    RESPONSES = pickle.load(f)
EOFError: Ran out of input`

**Comment by lkellar** [comment]
hmmmmm, I'll take a look at that real quick,

**Comment by lkellar** [comment]
what command did you use to run the virtual-assistant

**Comment by zpitroda** [comment]
just cd'd into the directory i had it in and ran `main.py`

**Comment by zpitroda** [comment]
`C:\Users\zpit3>cd C:\Users\zpit3\OneDrive\Documents\GitHub\virtual-assistant`

`C:\Users\zpit3\OneDrive\Documents\GitHub\virtual-assistant>main.py`

**Comment by lkellar** [comment]
K, I just committed a fix that should create the response_data, can you `git pull` and try again

**Comment by zpitroda** [comment]
thanks

**Comment by lkellar** [comment]
No Problem!

**Comment by zpitroda** [comment]
same thing:

C:\Users\zpit3\OneDrive\Documents\GitHub\virtual-assistant>main.py
Generating preferences...
Welcome to virtual-assistant setup, friend
Enter your nickname, or hit return and I'll keep calling you 'friend':
> test
Okay, test, here's some guidance:
 - At any time, you can tell me more about yourself and change your contact info
 - You can also type 'help' if you get hopelessly lost or want to know what I can do
Setup complete
Generating response data...
Traceback (most recent call last):
  File "C:\Users\zpit3\OneDrive\Documents\GitHub\virtual-assistant\main.py", line 91, in <module>
    with open(currentDir + '/response_data.p', 'a'):
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\zpit3\\OneDrive\\Documents\\GitHub\\virtual-assistant/response_data.p'

**Comment by lkellar** [comment]
ah, ok, I think i didn't apply the method we used earlier to everything, I'll fix that real quick

**Comment by lkellar** [comment]
quick question, what python version are you running?

**Comment by zpitroda** [comment]
3.6.6

**Comment by jpsank** [comment]
Does the project directory have sufficient read/write permissions? Try `chmod 777 virtual-assistant/`

**Comment by zpitroda** [comment]
I'm on windows, but yeah it should

**Comment by lkellar** [comment]
Found the bug, to find files, we were using the unix file paths, so when a windows machine tried to find a file, it broke, I replaced all instances of file finding with a cross-platform method.

Should work now
Sorry about all the bugs.

**Comment by zpitroda** [comment]
thanks!

**Comment by lkellar** [comment]
no problem!

**Comment by zpitroda** [comment]
still not working. I tried it on linux as well

![image](https://user-images.githubusercontent.com/30330004/42849269-22ee77f2-89e8-11e8-8864-0ca4330b7fcd.png)

**Comment by lkellar** [comment]
Very strange, I'll pop open a VM and try to replicate the error once I get home.

**Comment by zpitroda** [comment]
thanks

**Comment by lkellar** [comment]
What version of Windows are you running?

**Comment by zpitroda** [comment]
10

**Comment by zpitroda** [comment]
build 17134

**Comment by lkellar** [comment]
Hmmmm, weird, I tried running it on a Windows 10 vim and it ran fine. Is there anything notable or interesting about your setup?

**Comment by zpitroda** [comment]
huh. ill try it in a different directory

**Comment by zpitroda** [comment]
That worked! I'm not sure why it didnt in the github directory though, I even gave it admin rights. Sorry bout that, thanks for helping!

**Comment by katzrkool** [comment]
It fixed it?

**Comment by lkellar** [comment]
No problem!
